name: govis
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  dio: ^2.1.13
  logger: ^0.7.0+2
  flutter_bloc: ^2.0.0
  bloc: ^2.0.0
  equatable: ^1.0.0
  shimmer: ^1.0.0
  cached_network_image: ^2.0.0-rc.1
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: ^8.4.0
  throttling: ^0.8.0
  webview_flutter: ^0.3.17
  flushbar: ^1.9.1
  json_serializable: ^3.2.3
  firebase_messaging: ^5.1.5
  timeago: ^2.0.22
  animated_text_kit: ^1.3.1
  provider: ^3.1.0
  path_provider: ^1.3.0
  permission_handler: ^3.2.2
  open_file: ^2.0.3
  styled_widget: ^0.0.6
  time: ^1.2.0
  flutter_fadein: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
